from app.services.github_service import (
    create_branch,
    create_pull_request,
    get_base_branch_sha,
    upsert_file,
)
from app.services.terraform_generator import generate_terraform_files

async def provision_request_via_pull_request(input_data: dict) -> dict:
    branch_name = f"request/{input_data['requestId']}"
    base = await get_base_branch_sha()

    await create_branch(branch_name, base["sha"])

    files = generate_terraform_files(input_data)

    for file in files:
        await upsert_file(
            file["path"],
            file["content"],
            branch_name,
            f"Add Terraform stack for {input_data['requestId']}",
        )

    pr = await create_pull_request(
        branch_name,
        f"Provision {input_data['templateId']} for {input_data['requestId']}",
        "\n".join(
            [
                "## Infrastructure Request",
                "",
                f"- **Request ID:** {input_data['requestId']}",
                f"- **Provider:** {input_data['provider']}",
                f"- **Template:** {input_data['templateId']}",
                f"- **Requested By:** {input_data['requestedBy']}",
                f"- **Base Branch:** {base['branch']}",
                "",
                "This PR was auto-generated by the provisioning portal.",
            ]
        ),
    )

    return {
        "branchName": branch_name,
        "prUrl": pr["url"],
        "prNumber": pr["number"],
    }