from app.models.template_models import Template

templates: list[Template] = [
    Template(
        id="aws-s3-bucket",
        provider="aws",
        name="AWS S3 Bucket",
        description="Provision a secure S3 bucket",
        category="storage",
        terraform_module_path="../../modules/aws-s3-bucket",
        parameters=[
            {
                "name": "bucket_name",
                "label": "Bucket Name",
                "type": "string",
                "required": True,
                "placeholder": "my-app-results",
                "helperText": "Enter the base bucket name. A unique suffix will be appended automatically during provisioning.",
                "pattern": "^[a-z0-9]+(-[a-z0-9]+)+$",
                "patternErrorMessage": "Bucket name must use lowercase letters/numbers and hyphens, for example: app-dev-results",
            },
            {
                "name": "environment",
                "label": "Environment",
                "type": "select",
                "required": True,
                "options": ["dev", "agile", "prod"],
                "default": "dev",
                "helperText": "Target environment for this bucket.",
            },
            {
                "name": "versioning",
                "label": "Enable Versioning",
                "type": "boolean",
                "default": False,
            },
            {
                "name": "encryption_enabled",
                "label": "Enable Encryption",
                "type": "boolean",
                "default": False,
            },
            {
                "name": "website_hosting_enabled",
                "label": "Enable Static Website Hosting",
                "type": "boolean",
                "default": False,
            },
            {
                "name": "index_document",
                "label": "Index Document",
                "type": "string",
                "required": False,
                "placeholder": "index.html",
                "helperText": "Required only if website hosting is enabled.",
                "pattern": "^[A-Za-z0-9._/-]+$",
                "patternErrorMessage": "Index document may only contain letters, numbers, dots, underscores, hyphens, and slashes.",
                "showWhen": {
                    "field": "website_hosting_enabled",
                    "equals": True
                }
            },
            {
                "name": "error_document",
                "label": "Error Document",
                "type": "string",
                "required": False,
                "placeholder": "error.html",
                "helperText": "Optional. Used only if website hosting is enabled.",
                "pattern": "^[A-Za-z0-9._/-]+$",
                "patternErrorMessage": "Error document may only contain letters, numbers, dots, underscores, hyphens, and slashes.",
                "showWhen": {
                    "field": "website_hosting_enabled",
                    "equals": True
                }
            },
            {
                "name": "tag_owner",
                "label": "Tag: Owner",
                "type": "string",
                "required": True,
                "placeholder": "platform-team",
                "pattern": "^[A-Za-z0-9._-]{2,50}$",
            },
            {
                "name": "tag_cost_center",
                "label": "Tag: Cost Center",
                "type": "string",
                "required": True,
                "placeholder": "CC1234",
                "pattern": "^[A-Za-z0-9._-]{2,30}$",
            },
            {
                "name": "tag_project",
                "label": "Tag: Project",
                "type": "string",
                "required": True,
                "placeholder": "infra-demo",
                "pattern": "^[A-Za-z0-9._-]{2,50}$",
            },
            {
                "name": "estimated_storage_gb",
                "label": "Estimated Storage (GB)",
                "type": "number",
                "required": False,
                "default": 100,
                "estimationOnly": True,
                "min": 1,
                "max": 100000,
            },
            {
                "name": "estimated_monthly_put_requests",
                "label": "Estimated Monthly PUT Requests",
                "type": "number",
                "required": False,
                "default": 100000,
                "estimationOnly": True,
                "min": 0,
                "max": 1000000000,
            },
            {
                "name": "estimated_monthly_get_requests",
                "label": "Estimated Monthly GET Requests",
                "type": "number",
                "required": False,
                "default": 1000000,
                "estimationOnly": True,
                "min": 0,
                "max": 1000000000,
            },
        ],
    ),
    Template(
        id="aws-lambda-function",
        provider="aws",
        name="AWS Lambda Function",
        description="Provision a serverless Lambda function",
        category="compute",
        terraform_module_path="../../modules/aws-lambda-function",
        parameters=[
            {
                "name": "function_name",
                "label": "Function Name",
                "type": "string",
                "required": True,
            },
            {
                "name": "environment",
                "label": "Environment",
                "type": "select",
                "required": True,
                "options": ["dev", "agile", "prod"],
            },
            {
                "name": "versioning",
                "label": "Enable Versioning",
                "type": "boolean",
                "default": True,
            },
        ],
    ),
    Template(
        id="aws-api-gateway",
        provider="aws",
        name="AWS API Gateway",
        description="Provision a REST API Gateway",
        category="network",
        terraform_module_path="../../modules/aws-api-gateway",
        parameters=[
            {
                "name": "api_name",
                "label": "API Name",
                "type": "string",
                "required": True,
            },
            {
                "name": "environment",
                "label": "Environment",
                "type": "select",
                "required": True,
                "options": ["dev", "agile", "prod"],
            },
            {
                "name": "cors",
                "label": "Enable CORS",
                "type": "boolean",
                "default": True,
            },
        ],
    ),
    Template(
        id="aws-ec2-instance",
        provider="aws",
        name="AWS EC2 Instance",
        description="Provision an EC2 instance",
        category="compute",
        terraform_module_path="../../modules/aws-ec2-instance",
        parameters=[
            {
                "name": "instance_name",
                "label": "Instance Name",
                "type": "string",
                "required": True,
            },
            {
                "name": "instance_type",
                "label": "Instance Type",
                "type": "select",
                "required": True,
                "options": ["t3.small", "t3.medium", "t3.large"],
            },
            {
                "name": "ebs_size",
                "label": "EBS Size (GB)",
                "type": "number",
                "required": True,
                "default": 20,
            },
        ],
    ),
    Template(
        id="azure-storage-account",
        provider="azure",
        name="Azure Storage Account",
        description="Provision an Azure Storage Account",
        category="storage",
        terraform_module_path="../../modules/azure-storage-bucket",
        parameters=[
            {
                "name": "account_name",
                "label": "Account Name",
                "type": "string",
                "required": True,
            },
            {
                "name": "location",
                "label": "Location",
                "type": "select",
                "required": True,
                "options": ["eastus", "westus", "centralus"],
            },
            {
                "name": "sku",
                "label": "SKU",
                "type": "select",
                "required": True,
                "options": ["Standard_LRS", "Standard_GRS", "Premium_LRS"],
            },
        ],
    ),
]