import {
  createBranch,
  createPullRequest,
  getBaseBranchSha,
  upsertFile,
} from "./githubService.js";
import { generateTerraformFiles } from "./terraformGenerator.js";

type ProvisionRequestInput = {
  requestId: string;
  provider: string;
  templateId: string;
  moduleSource: string;
  parameters: Record<string, unknown>;
  requestedBy: string;
  createdAt: string;
};

export async function provisionRequestViaPullRequest(
  input: ProvisionRequestInput
) {
  const branchName = `request/${input.requestId}`;
  const base = await getBaseBranchSha();

  await createBranch(branchName, base.sha);

  const files = generateTerraformFiles({
    requestId: input.requestId,
    provider: input.provider,
    templateId: input.templateId,
    moduleSource: input.moduleSource,
    parameters: input.parameters,
    requestedBy: input.requestedBy,
    createdAt: input.createdAt,
  });

  for (const file of files) {
    await upsertFile(
      file.path,
      file.content,
      branchName,
      `Add Terraform stack for ${input.requestId}`
    );
  }

  const pr = await createPullRequest(
    branchName,
    `Provision ${input.templateId} for ${input.requestId}`,
    [
      `## Infrastructure Request`,
      ``,
      `- **Request ID:** ${input.requestId}`,
      `- **Provider:** ${input.provider}`,
      `- **Template:** ${input.templateId}`,
      `- **Requested By:** ${input.requestedBy}`,
      `- **Base Branch:** ${base.branch}`,
      ``,
      `This PR was auto-generated by the provisioning portal.`,
    ].join("\n")
  );

  return {
    branchName,
    prUrl: pr.url,
    prNumber: pr.number,
  };
}